name: main

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
#    permissions:
#      metadata: read
#      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Run main build runner
        env:
          CI_TOOL: github
          NATIVE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MONOREPO_TOKEN }}
        run: ./tools/ci/core/build.sh
