name: main

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run main build runner
        env:
          CI_TOOL: github
          REAL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: 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
        run: ./tools/ci/core/build.sh